
import { useLocation } from "react-router-dom";
import { Link } from "react-router-dom";
import PageLayout from "../components/layout/PageLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, Target, Zap, TrendingUp, Users, Shield, ChevronRight } from "lucide-react";
import { Helmet } from "react-helmet-async";
import { 
  generateArticleSchema, 
  generateBreadcrumbSchema, 
  generateEnhancedFAQSchema,
  generateOrganizationSchema
} from "@/lib/utils";

const AIAndDigitalMarketing = () => {
  const location = useLocation();
  const canonicalUrl = `https://digitalfrontier.app${location.pathname}`;

  const aiMarketingAreas = [
    {
      id: 1,
      title: "AI-Powered Ad Targeting",
      description: "Machine learning algorithms that analyze user behavior and demographics to deliver personalized advertising experiences.",
      example: "Dynamic audience segmentation and predictive targeting based on user journey analysis.",
      benefit: "Up to 40% improvement in conversion rates through precision targeting.",
      icon: <Target className="h-6 w-6 text-blue-400" />,
      link: "/ad-funnel-blueprint"
    },
    {
      id: 2,
      title: "Generative Content Creation",
      description: "AI systems that create marketing copy, images, and video content tailored to specific audiences and campaigns.",
      example: "Automated A/B testing of ad creative variations generated by AI for different market segments.",
      benefit: "70% reduction in content creation time while maintaining quality and relevance.",
      icon: <Brain className="h-6 w-6 text-purple-400" />,
      link: "/resources/content-creation-agent"
    },
    {
      id: 3,
      title: "Predictive Analytics",
      description: "Advanced analytics that forecast customer behavior, campaign performance, and market trends.",
      example: "Customer lifetime value prediction and churn prevention through behavioral pattern analysis.",
      benefit: "25% increase in customer retention through proactive engagement strategies.",
      icon: <TrendingUp className="h-6 w-6 text-green-400" />,
      link: "/technical"
    },
    {
      id: 4,
      title: "Real-Time Optimization",
      description: "AI systems that continuously adjust campaigns based on performance data and market conditions.",
      example: "Automatic bid adjustments and budget reallocation across channels for maximum ROI.",
      benefit: "30% improvement in campaign efficiency through continuous optimization.",
      icon: <Zap className="h-6 w-6 text-yellow-400" />,
      link: "/generative-engine-optimization"
    },
    {
      id: 5,
      title: "Customer Journey Mapping",
      description: "AI-driven analysis of customer touchpoints to optimize the entire marketing funnel.",
      example: "Personalized content delivery at each stage of the customer journey based on behavior signals.",
      benefit: "50% improvement in lead quality through optimized customer experience paths.",
      icon: <Users className="h-6 w-6 text-cyan-400" />,
      link: "/answer-engine-optimization"
    },
    {
      id: 6,
      title: "Ethical AI Implementation",
      description: "Responsible AI practices that ensure fair and transparent marketing while protecting user privacy.",
      example: "Bias detection systems and privacy-first targeting that builds consumer trust.",
      benefit: "Enhanced brand reputation and compliance with evolving data protection regulations.",
      icon: <Shield className="h-6 w-6 text-emerald-400" />,
      link: "/ai-bias-in-advertising"
    },
  ];

  // Generate structured data
  const articleSchema = {
    ...generateArticleSchema(
      "AI & Digital Marketing Revolution - Transform Your Marketing Strategy",
      "Discover how artificial intelligence is revolutionizing digital marketing through AI-powered targeting, content creation, predictive analytics, and ethical AI implementation. Learn from Digital Frontier Company's expertise.",
      "Digital Frontier Company",
      "Digital Frontier Company",
      "/lovable-uploads/2486421b-6ca3-4c32-b686-a49ac0da182b.png",
      "2025-01-13",
      "2025-01-13",
      canonicalUrl
    ),
    wordCount: 850,
    inLanguage: "en-US",
    image: [
      "https://digitalfrontier.app/lovable-uploads/2486421b-6ca3-4c32-b686-a49ac0da182b.png"
    ]
  };

  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: "https://digitalfrontier.app" },
    { name: "AI & Digital Marketing", url: canonicalUrl }
  ]);

  const faqSchema = generateEnhancedFAQSchema([
    {
      question: "What is AI-powered digital marketing?",
      answer: "AI-powered digital marketing uses artificial intelligence and machine learning to automate and optimize marketing processes, including targeting, content creation, predictive analytics, and personalization to improve campaign performance and customer engagement.",
      category: "AI Marketing Basics"
    },
    {
      question: "How can AI improve marketing ROI?",
      answer: "AI improves marketing ROI through precision targeting (up to 40% conversion improvement), automated content creation (70% time reduction), predictive analytics (25% retention increase), and real-time optimization (30% efficiency improvement).",
      category: "ROI & Performance"
    },
    {
      question: "What are recommender systems in digital marketing?",
      answer: "Recommender systems are AI algorithms that analyze user behavior and preferences to suggest personalized content, products, or services, significantly improving user engagement and conversion rates in digital marketing campaigns.",
      category: "AI Technology"
    }
  ]);

  const organizationSchema = generateOrganizationSchema();

  const webPageSchema = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": canonicalUrl,
    url: canonicalUrl,
    name: "AI & Digital Marketing Revolution | Digital Frontier",
    description: "Transform your marketing strategy with AI-powered solutions. Expert insights on artificial intelligence in digital marketing from Digital Frontier Company.",
    isPartOf: {
      "@type": "WebSite",
      "@id": "https://digitalfrontier.app/#website"
    },
    about: {
      "@type": "Thing",
      name: "AI Digital Marketing"
    },
    mainEntity: {
      "@type": "Article",
      "@id": `${canonicalUrl}#article`
    }
  };

  return (
    <PageLayout 
      title="AI in Digital Marketing: Complete Strategy Guide with Proven Techniques & Advanced Implementation Tips | Transform Your Business"
      subtitle="Master artificial intelligence in marketing with expert strategies, practical implementation guides, and proven techniques that drive measurable results"
      currentPath={location.pathname}
    >
      
      <div className="mb-8">
        <p className="text-slate-300 text-lg leading-relaxed">
          Artificial Intelligence is fundamentally reshaping how we approach <strong>digital marketing</strong>. From predictive analytics 
          to personalized content generation, AI technologies are enabling marketers to create more effective, 
          efficient, and ethical campaigns that deliver superior results. At <span className="text-[#00BFFF] font-semibold">Digital Frontier Company</span>, 
          we're at the forefront of this AI marketing revolution.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        {aiMarketingAreas.map((item) => (
          <Link to={item.link} key={item.id}>
            <Card className="bg-slate-800/80 border-slate-700 hover:border-[#00BFFF] transition-all duration-300 group h-full hover:transform hover:scale-105">
              <CardHeader className="pb-2">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-slate-700/50 rounded-md group-hover:bg-[#00BFFF]/20 transition-colors">
                    {item.icon}
                  </div>
                  <CardTitle className="text-lg text-slate-100 group-hover:text-[#00BFFF] transition-colors">
                    {item.title}
                  </CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-slate-300 mb-3">{item.description}</p>
                <CardDescription className="text-slate-400 mb-2">
                  <span className="font-semibold text-blue-400">Example:</span> {item.example}
                </CardDescription>
                <CardDescription className="text-slate-400">
                  <span className="font-semibold text-emerald-400">Impact:</span> {item.benefit}
                </CardDescription>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>

      {/* New Recommender Systems Section */}
      <div className="mb-8 p-6 bg-gradient-to-r from-blue-900/30 to-purple-900/30 border border-slate-700 rounded-xl">
        <h3 className="text-2xl font-semibold text-[#00BFFF] mb-4 flex items-center gap-2">
          <Brain className="h-6 w-6" />
          Advanced AI Research & Development
        </h3>
        <p className="text-slate-300 mb-4">
          Dive deeper into cutting-edge AI research that's shaping the future of digital marketing. Our advanced research covers 
          recommender system generalization, predictive modeling, and automated machine learning techniques.
        </p>
        <Link 
          to="/recommender-system-generalization" 
          className="inline-flex items-center gap-2 px-6 py-3 bg-[#00BFFF] hover:bg-[#0099CC] text-white font-semibold rounded-lg transition-colors duration-300"
        >
          Explore Recommender Systems Research
          <ChevronRight className="h-4 w-4" />
        </Link>
      </div>
      
      <div className="mt-8 p-6 bg-slate-800/60 border border-slate-700 rounded-xl">
        <h3 className="text-xl font-semibold text-[#00BFFF] mb-3">The Future of AI-Driven Marketing</h3>
        <p className="text-slate-300 mb-4">
          As AI technologies continue to evolve, we're seeing unprecedented opportunities for marketers to create 
          more personalized, effective, and ethical campaigns. The key to success lies in understanding both the 
          technical capabilities and the strategic implications of AI implementation in digital marketing.
        </p>
        <p className="text-slate-300 mb-4">
          Companies that embrace <strong>AI-driven marketing strategies</strong> while maintaining ethical standards and focusing on 
          genuine customer value will emerge as leaders in the digital marketplace of tomorrow. <span className="text-[#00BFFF] font-semibold">Digital Frontier Company</span> 
          is committed to helping businesses navigate this transformation successfully.
        </p>
        
        <div className="flex flex-wrap justify-center gap-4 mt-6">
          <Link to="/ad-funnel-blueprint" className="px-4 py-2 bg-blue-600/30 hover:bg-blue-600/50 rounded-md text-blue-300 transition-colors">
            Start with AI Ad Funnels
          </Link>
          <Link to="/generative-engine-optimization" className="px-4 py-2 bg-purple-600/30 hover:bg-purple-600/50 rounded-md text-purple-300 transition-colors">
            Explore GEO
          </Link>
          <Link to="/resources/content-creation-agent" className="px-4 py-2 bg-green-600/30 hover:bg-green-600/50 rounded-md text-green-300 transition-colors">
            Content Creation Tools
          </Link>
          <Link to="/psychological-digital-marketing-insights" className="px-4 py-2 bg-orange-600/30 hover:bg-orange-600/50 rounded-md text-orange-300 transition-colors">
            Psychology Insights
          </Link>
          <Link to="/emotional-marketing-playbook" className="px-4 py-2 bg-red-600/30 hover:bg-red-600/50 rounded-md text-red-300 transition-colors">
            Emotional Marketing
          </Link>
          <Link to="/memphis-digital-marketing" className="px-4 py-2 bg-cyan-600/30 hover:bg-cyan-600/50 rounded-md text-cyan-300 transition-colors">
            Memphis Services
          </Link>
        </div>
      </div>
    </PageLayout>
  );
};

export default AIAndDigitalMarketing;
