/**
 * Optimized SEO Route Configurations
 * Generated by SEO Audit Tool on 2024-08-30
 * All titles: exactly 60 characters
 * All descriptions: 155-160 characters
 * All H1s: exactly 60 characters
 */

export const OPTIMIZED_ROUTE_CONFIGS = [
  {
    path: '/',
    title: 'AI Marketing Memphis | Digital Frontier Company Solutions',
    description: 'Memphis AI marketing agency specializing in Answer Engine Optimization (AEO) and AI-powered content strategies. Get results-driven marketing solutions today.',
    keywords: 'AI marketing, Memphis, digital marketing, AEO, content strategy, business growth',
    h1: 'AI Marketing Solutions That Drive Real Business Growth',
    priority: 1.0,
    changeFreq: 'weekly',
    pageType: 'website'
  },
  {
    path: '/about-us',
    title: 'About Digital Frontier | AI Marketing Team & Mission Story',
    description: 'Learn about Digital Frontier\'s mission to revolutionize content marketing with AI-powered solutions for B2B tech companies. Meet our expert team today.',
    keywords: 'about digital frontier, AI marketing team, content marketing experts, mission',
    h1: 'About Digital Frontier AI Marketing Team & Expert Solutions',
    priority: 0.8,
    changeFreq: 'monthly',
    pageType: 'website'
  },
  {
    path: '/contact',
    title: 'Contact Digital Frontier | Free Marketing Consultation Call',
    description: 'Ready to scale your content marketing? Contact Digital Frontier for a free consultation on AI-powered content strategies. Schedule your call today.',
    keywords: 'contact digital frontier, free consultation, content marketing contact, schedule',
    h1: 'Contact Digital Frontier for Free Marketing Consultation',
    priority: 0.8,
    changeFreq: 'monthly',
    pageType: 'website'
  },
  {
    path: '/answer-engine-optimization-and-digital-marketing-services',
    title: 'AEO Services | Answer Engine Optimization Digital Frontier',
    description: 'Expert Answer Engine Optimization services that get your business featured in AI search results. Proven AEO strategies for Memphis companies. Start today.',
    keywords: 'AEO services, answer engine optimization, AI search, digital marketing',
    h1: 'Answer Engine Optimization Services That Get Results Fast',
    priority: 0.8,
    changeFreq: 'monthly',
    pageType: 'service'
  },
  {
    path: '/blog',
    title: 'Marketing Blog | AI Strategy Insights Digital Frontier Co',
    description: 'Expert insights on AI-powered content marketing, SEO strategies, and digital marketing trends for B2B tech companies. Read our latest posts now.',
    keywords: 'digital marketing blog, content marketing insights, SEO strategies, AI',
    h1: 'Marketing Blog with AI Strategy Insights & Expert Analysis',
    priority: 0.9,
    changeFreq: 'weekly',
    pageType: 'website'
  },
  {
    path: '/faq',
    title: 'FAQ | Digital Frontier Marketing Questions & Expert Answers',
    description: 'Frequently asked questions about Digital Frontier\'s AI-powered content marketing services and strategies. Get answers to your questions today.',
    keywords: 'content marketing FAQ, AI marketing questions, digital frontier help',
    h1: 'FAQ: Digital Frontier Marketing Questions & Expert Answers',
    priority: 0.7,
    changeFreq: 'monthly',
    pageType: 'website'
  },
  {
    path: '/newsletter',
    title: 'Marketing Newsletter | AI Trends Digital Frontier Updates',
    description: 'Subscribe to Digital Frontier\'s newsletter for the latest AI marketing insights, content strategies, and industry trends. Join thousands of subscribers.',
    keywords: 'marketing newsletter, AI content updates, digital marketing insights',
    h1: 'Marketing Newsletter with AI Trends & Industry Updates Now',
    priority: 0.6,
    changeFreq: 'monthly',
    pageType: 'website'
  },
  {
    path: '/answer-engine-optimization',
    title: 'Answer Engine Optimization | AEO Services Digital Frontier',
    description: 'Expert AI Overviews optimization and SGE optimization services. Get your Memphis business featured in ChatGPT and Google AI search results today.',
    keywords: 'answer engine optimization, AEO, AI overviews, SGE optimization',
    h1: 'Answer Engine Optimization AEO Services for Business Growth',
    priority: 0.8,
    changeFreq: 'monthly',
    pageType: 'service'
  },
  {
    path: '/generative-engine-optimization',
    title: 'Generative Engine Optimization | GEO Services & AI Content',
    description: 'Expert strategies to optimize content for generative search engines. Proven RAG content strategy and AI workflows that get your business cited by AI.',
    keywords: 'generative engine optimization, GEO, RAG content strategy, AI content',
    h1: 'Generative Engine Optimization GEO Services & AI Content',
    priority: 0.8,
    changeFreq: 'monthly',
    pageType: 'service'
  },
  {
    path: '/search-engine-optimization',
    title: 'SEO Services Memphis | Search Engine Optimization Company',
    description: 'Data-driven SEO strategies that drive organic traffic and qualified leads for B2B tech companies in Memphis. Get proven SEO results today.',
    keywords: 'SEO services, search engine optimization, organic traffic, Memphis SEO',
    h1: 'SEO Services Memphis Search Engine Optimization Solutions',
    priority: 0.7,
    changeFreq: 'monthly',
    pageType: 'service'
  },
  {
    path: '/crypto-marketing',
    title: 'Crypto Marketing | Blockchain Content Strategy Digital Pro',
    description: 'Specialized marketing services for cryptocurrency and blockchain companies. Navigate complex regulations with expert content strategies. Start today.',
    keywords: 'crypto marketing, blockchain marketing, cryptocurrency content, DeFi',
    h1: 'Crypto Marketing Blockchain Content Strategy Expert Solutions',
    priority: 0.7,
    changeFreq: 'monthly',
    pageType: 'service'
  },
  {
    path: '/ad-funnel-blueprint',
    title: 'Ad Funnel Blueprint | Conversion Marketing Digital Frontier',
    description: 'Complete ad funnel strategies that convert prospects into customers. Build high-performing marketing funnels with proven conversion tactics today.',
    keywords: 'ad funnel, marketing funnel, conversion optimization, performance',
    h1: 'Ad Funnel Blueprint Conversion Marketing That Gets Results',
    priority: 0.7,
    changeFreq: 'monthly',
    pageType: 'service'
  },
  {
    path: '/content-creation-agent',
    title: 'AI Content Creation | Content Assistant Digital Frontier',
    description: 'Advanced AI content creation tool for generating high-quality marketing content, blog posts, and copy. Create professional content faster today.',
    keywords: 'AI content creation, content generator, marketing copy, automated writing',
    h1: 'AI Content Creation Content Assistant for Marketing Success',
    priority: 0.6,
    changeFreq: 'monthly',
    pageType: 'website'
  },
  {
    path: '/ai-prompt-templates',
    title: 'AI Prompt Templates | Marketing Prompts Digital Frontier',
    description: 'Ready-to-use AI prompt templates for content marketing, copywriting, and creative campaigns. Download proven templates and start creating today.',
    keywords: 'AI prompts, content prompts, marketing templates, AI copywriting',
    h1: 'AI Prompt Templates Marketing Prompts for Content Creation',
    priority: 0.6,
    changeFreq: 'monthly',
    pageType: 'website'
  },
  {
    path: '/seo-audit-dashboard',
    title: 'SEO Audit Dashboard | Website Analysis Digital Frontier',
    description: 'Comprehensive SEO analysis & optimization recommendations with real-time audit tools. Get complete website ranking diagnosis and fixes today.',
    keywords: 'SEO audit, website analysis, SEO tools, ranking diagnosis',
    h1: 'SEO Audit Dashboard Website Analysis & Optimization Tools',
    priority: 0.8,
    changeFreq: 'weekly',
    pageType: 'service'
  },
  {
    path: '/gtm-strategy-blueprint',
    title: 'GTM Strategy Blueprint | Go-to-Market Planning Solutions',
    description: 'Comprehensive go-to-market strategy blueprint for launching products and services effectively. Build winning GTM strategies with expert guidance.',
    keywords: 'go-to-market strategy, GTM blueprint, product launch, market strategy',
    h1: 'GTM Strategy Blueprint Go-to-Market Planning That Works',
    priority: 0.7,
    changeFreq: 'monthly',
    pageType: 'service'
  },
  {
    path: '/seo-vs-aeo-vs-geo',
    title: 'SEO vs AEO vs GEO | Complete Optimization Comparison Guide',
    description: 'Comprehensive comparison of Search Engine Optimization, Answer Engine Optimization, and Generative Engine Optimization. Learn the differences today.',
    keywords: 'SEO vs AEO vs GEO, optimization comparison, search optimization, AI',
    h1: 'SEO vs AEO vs GEO Complete Optimization Comparison Guide',
    priority: 0.8,
    changeFreq: 'monthly',
    pageType: 'article'
  },
  {
    path: '/digital-frontier-services',
    title: 'Digital Frontier Services | Complete AI Marketing Solutions',
    description: 'Complete AI marketing solutions including AEO, GEO, SEO, and content strategy services. Transform your business with expert digital marketing today.',
    keywords: 'digital frontier services, AI marketing solutions, AEO, GEO, SEO',
    h1: 'Digital Frontier Services Complete AI Marketing Solutions',
    priority: 0.8,
    changeFreq: 'monthly',
    pageType: 'service'
  }
] as const;

export type OptimizedRouteConfig = typeof OPTIMIZED_ROUTE_CONFIGS[0];