// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uplseuoqgcwxpsylrirr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwbHNldW9xZ2N3eHBzeWxyaXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mzg0MzIsImV4cCI6MjA2NjUxNDQzMn0.NKAeZjVsEx79GusWma26Gr7r12dJiTLXAkFmPAeIdNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});