// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzoqcxttvnqsvezqvjec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6b3FjeHR0dm5xc3ZlenF2amVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTA0NjksImV4cCI6MjA3MzU2NjQ2OX0.kr9jEi_2ofB1btEghhc4ij23R2IsxwiiWjImwfsFE0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});